name: 'create-report'
description: 'An action to create a generic run report'

branding:
  icon: 'file-text'
  color: 'green'

# TODO: Specify version
inputs:
  report-title:
    description: "Title of the report"
    required: true
  report-summary:
    description: "Summary of the report."
    required: true

runs:
  using: "composite"
  steps:
    - name: Create report
      run: |
        swift run ghchecks create-report \
        --report-title "${{ inputs.report-title }} " \
        --report-summary "${{ inputs.report-summary }}" \
        --repository "${{ github.repository }}" \
        --head-sha "${{ github.event.pull_request.head.sha }}" \
        --github-token "${{ github.token }}"
      shell: bash
